function s = empty_trace
  s.range = [];
  s.force = []; 
  s.deltax = [];
  s.time = [];
  s.ripx = [];
  s.fdot = [];
  s.fstep = [];
  s.rip_index = [];  
  s.pfx_b = [];     
  s.pfx_a = [];  
  s.dt    = [];
  s.temperature = [];
  s.noise = [];
  s.fitrange = [];
  s.topforce = [];
  s.pullingspeed = [];
  s.filename = [];
  s.cycleno = [];
  s.work = [];
end